image_dir = "C:/test/input_images"  # 待测图像所在文件夹
order_by = 0  # 输入图像的重排序方式；0：文件名，1：创建时间，2：修改时间
descending = false  # 是否按降序重排序
mode = 0  # 亮度衡量方法；0：RGB总和，1：R，2：G，3：B
# top_left_x = 0  # ROI的左上角x坐标；若无需截取ROI，可注释掉
# top_left_y = 0  # ROI的左上角y坐标；若无需截取ROI，可注释掉
# width = 0  # ROI的宽度；若无需截取ROI，可注释掉
# height = 0  # ROI的高度；若无需截取ROI，可注释掉
output_data_path = "C:/test/output_data.csv"  # 输出数据文件的路径；若无需输出数据文件，可注释掉
output_plot_path = "C:/test/output_plot.svg"  # 输出折线图的路径；若无需输出折线图，可注释掉
